# Generated by Django 5.1.6 on 2025-05-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montajes', '0002_montaje_fecha_finalizacion_montaje_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CPU', 'Procesador'), ('RAM', 'Memoria RAM'), ('GPU', 'Tarjeta Gráfica'), ('SSD', 'Disco SSD'), ('HDD', 'Disco Duro'), ('MOB', 'Placa Base'), ('PSU', 'Fuente de Alimentación'), ('COOL', 'Sistema de Refrigeración'), ('CASE', 'Caja/Chasis'), ('OTHER', 'Otro')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloOrdenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('componentes', models.ManyToManyField(related_name='modelos_ordenador', to='montajes.componentehardware')),
            ],
        ),
        migrations.AddField(
            model_name='montaje',
            name='modelo_ordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montajes', to='montajes.modeloordenador'),
        ),
    ]
