# Generated by Django 5.1.6 on 2025-05-18 17:05

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('montajes', '0003_componentehardware_modeloordenador_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para añadir las columnas si no existen
            """
            ALTER TABLE montajes_montaje 
            ADD COLUMN IF NOT EXISTS fecha_inicio DATETIME NULL,
            ADD COLUMN IF NOT EXISTS fecha_finalizacion DATETIME NULL,
            ADD COLUMN IF NOT EXISTS montador_id INTEGER NULL;
            """,
            # SQL para revertir los cambios
            """
            ALTER TABLE montajes_montaje 
            DROP COLUMN IF EXISTS fecha_inicio,
            DROP COLUMN IF EXISTS fecha_finalizacion,
            DROP COLUMN IF EXISTS montador_id;
            """
        ),
        # Definir las relaciones en Django
        migrations.AlterField(
            model_name='montaje',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
    ]
